Update Jenkinsfile

diff --git a/US_PROD_Schema/Jenkinsfile b/US_PROD_Schema/Jenkinsfile
--- a/US_PROD_Schema/Jenkinsfile
+++ b/US_PROD_Schema/Jenkinsfile
@@ -18,8 +18,17 @@ pipeline {
                     export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
 
                     echo "Current directory: $(pwd)"
-                    ls -l
-                    python3 run_all_json_in_folder.py
+                  
+                    python3 run_all_json_in_folder.py > output.log 2>&1
+                    EXIT_CODE=$?
+                 if [ $EXIT_CODE -ne 0 ]; then
+                        echo "Python script failed with exit code $EXIT_CODE"
+                        echo "Last 20 lines of output:"
+                        tail -n 20 output.log
+                        exit $EXIT_CODE
+                    else
+                        echo "Python script completed successfully"
+                    fi
                     '''
                 }
             }
